# 🗄️ DATABASE (Supabase / PostgreSQL)
spring.datasource.url=jdbc:postgresql://postgres.dpgxndwhljzpiwymqqzx:ad06ykkG8w5TcFH9@aws-1-ap-southeast-2.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.dpgxndwhljzpiwymqqzx
spring.datasource.password=ad06ykkG8w5TcFH9

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ☁️ SUPABASE STORAGE CONFIG
supabase.url=https://dpgxndwhljzpiwymqqzx.supabase.co
supabase.bucket=uploads
supabase.apiKey=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRwZ3huZHdobGp6cGl3eW1xcXp4Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NDM2MDQ4OSwiZXhwIjoyMDg5OTM2NDg5fQ.J6d-_KM1YPGFJNqh7wOtCk3vZszLbLVPNB2jGVivKRI

# 🔐 JWT Secret
jwt.secret=5Ig7dHBhWK2ofw49FFaACr0k/165c4VTEjR1pLitqR0tWdlfzRyiZkzXdUIjdtvn3XQcSCRA4sMnO7vNEKG0cg==
jwt.expiration=86400000
